<?php

namespace AppBundle\Repository;

use Symfony\Component\Validator\Constraints\Email;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
