# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  AppBundle\Controller\RegistrationController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']