# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
  images_directory: '%kernel.project_dir%/src/AppBundle/Resources/public/images'

services:
  AppBundle\Controller\RegistrationController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    autowire: true
    tags: ['controller.service_arguments']
